language: node_js
node_js:
    - "4"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE electron_test;'
  - chmod 0777 ./node_modules/.bin/mocha
install:
    npm install -g npm@latest
    npm --version
    npm install --registry http://registry.npmjs.org
script:
    - sudo $(which npm) test